### ISSUE TITLE
Running Environment Inquiry

### ISSUE THREAD

**Issue by Easypiggy** [westerndigitalcorporation/ufs-tool#30]
Hi Arthur and Avri,

I just found your great ufs tools here, and was surprised by its powerful functions.
But I met some issues when trying to apply them on KIOXIA(TOSHIBA)'s UFS.
So I've got a little question about this tool, is it support WD's UFS only? 
Howerver since both WD/KIOXIA are using BiCS NAND now, if it's WD support only, is this caused by UFS Controler difference or what? By the way, it used to successfully run on Samsung's cellphone (Qualcomm SoC) with Samsung's UFS, so this is quite confusing to me.

The test environment I used are:
1. Hikey 960 Brd with Hisilicon's Soc, KIOXIA UFS2.0/2.1, Ubuntu 20 arm64 System
2. Qualcomm MSM8250(Snap Dragon 865) Dev Brd, KIOXIA UFS3.1, Android Dev System (Qualcomm revised linux 4.19 Kernel)
3. Xiaomi 9 cellphone, Qualcomm Snap Dragon 835, KIOXIA UFS2.1, Android 10 System (MIUI, Qualcomm Kernel Probably)

The cases are that, no matter what Env I use, the response of the tool is always like these text below:

`
root@hostname:/Tools$ ./ufs-utils vendor -p /dev/sdd

Start : do_vendor
Start : read_buffer

Start : send_scsi_cmd cmd = 3c len 512 sg_type 0

writing file scsi_cmd_cdb_1.bin length=10

Err: SG_IO READ BUFFER data error ret -1
`
No matter what CMD I tried, what sdx/0:0:0:x device I used, what Env I used, what chmod level been set, the results are all the same/similar as these text, with a blank Bin file generated under the run directory. I doubted if it's a Linux Kernel SG_IO issue?

I've also noticed this in your README.md:
"a) Read/Write device flags, attributes & descriptors by using the BSG infrastructure in linux kernel (applied to 5.1 rc1)
Due to the issues in UFS BSG driver, the following patch have to be applied:"

Could this be the cause? Since the patch is unused in my Env, and the only Kernel I'm sure is 4.19, lower than 5.1.
Or do you have any idea about this issue? Or if it's convenient for you to share your Env Info/give suggestion?
Besides, If the patch is strictly required, do this means that only devices with Dev ver. Android/Original Linux Based can be used?

Sorry, I've got too much questions.
I would be really appreciated if you can reply me when you are free,
Thank you!!!

EasyPiggy

**Comment by arthur-simchaev-sndk** [comment]
Hi EasyPiggy
See the comments inline

Regards
Arthur

From: Easypiggy ***@***.***>
Sent: Tuesday, March 16, 2021 5:45 AM
To: westerndigitalcorporation/ufs-utils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [westerndigitalcorporation/ufs-utils] Running Environment Inquiry (#30)

CAUTION: This email originated from outside of Western Digital. Do not click on links or open attachments unless you recognize the sender and know that the content is safe.


Hi Arthur and Avri,

I just found your great ufs tools here, and was surprised by its powerful functions.
But I met some issues when trying to apply them on KIOXIA(TOSHIBA)'s UFS.
So I've got a little question about this tool, is it support WD's UFS only?

[Arthur] This is generic tool which implemented according to the UFS Jedec spec.

And this is support all UFS vendors

Howerver since both WD/KIOXIA are using BiCS NAND now, if it's WD support only, is this caused by UFS Controler difference or what? By the way, it used to be successed runing on Samsung's cellphone (Qualcomm SoC) with Samsung's UFS, so this is quite confusing to me.

The test environment I used are:

  1.  Hikey 960 Brd with Hisilicon's Soc, KIOXIA UFS2.0/2.1, Ubuntu 20 arm64 System
  2.  Qualcomm MSM8250(Snap Dragon 865) Dev Brd, KIOXIA UFS3.1, Android Dev System (Qualcomm revised linux 4.19 Kernel)
  3.  Xiaomi 9 cellphone, Qualcomm Snap Dragon 835, KIOXIA UFS2.1, Android 10 System (MIUI, Qualcomm Kernel Probably)

The cases are that, no matter what Env I use, the response of the tool is always like these text below:

`
***@***.***:/Tools$ ./ufs-utils vendor -p /dev/sdd

Start : do_vendor
Start : read_buffer

Start : send_scsi_cmd cmd = 3c len 512 sg_type 0

writing file scsi_cmd_cdb_1.bin length=10

Err: SG_IO READ BUFFER data error ret -1

[Arthur] See the help of the command. : ./ufs-utils vendor -h

In case you want using sg_io ver3 (e.g. /dev/sdd) , you should use the -g1 option. E.g.:

./ufs-utils  vendor -i buf_id -O buf_ofset  -p /dev/sdd  -g 1



`
No matter what CMD I tried, what sdx/0:0:0:x device I used, what Env I used, what chmod level been set, the results are all the same/similar as these text, with a blank Bin file generated under the run directory. I doubted if it's a Linux Kernel SG_IO issue?

I've also noticed this in your README.md:
"a) Read/Write device flags, attributes & descriptors by using the BSG infrastructure in linux kernel (applied to 5.1 rc1)
Due to the issues in UFS BSG driver, the following patch have to be applied:"

Could this be the cause? Since the patch is unused in my Env, and the only Kernel I'm sure is 4.19, lower than 5.1.
Or do you have any idea about this issue? Or if it's convenient for you to share your Env Info/give suggestion?
Besides, If the patch is strictly required, do this means that only devices with Dev ver. Android/Original Linux Based can be used?

[Arthur] In order to read/write device configuration, you should  have ufs bsg infrastructure in your kernel. You have 2 option to do it:

  1.  Apply ufs-bdg patches to your kernel
  2.  Upgrade your kernel in HiKey960 to 5.4 linux mainline . ( See the instructions in Hikey 960 sites)

Sorry, I've got too much questions.
I would be really appreciated if you can reply me when you are free,
Thank you!!!

EasyPiggy

**Comment by Easypiggy** [comment]
Hi Arthur,


Thank you so much for your quick response!

Per this CMD: [./ufs-utils  vendor -i buf_id -O buf_ofset  -p /dev/sdd  -g 1],
I've also tried before, sorry for the improper example I used in the last comment. (also tried other function, similar response)
Though neither I use sg_io ver3 + "-g 1" with dev/sdx nor default sg_io ver4 with /dev/bsg/0:0:0:x, the result are almost the same, showed as below:
[sg ver 4]:
Err: Command fail with status 1, senseKey Illegal Request, asc 0x24, ascq 0x00
Err: SG_IO READ BUFFER data error ret -22
[sg ver 3]:
Err: Command fail with status 2, senseKey Illegal Request, asc 0x24, ascq 0x00
Err: SG_IO READ BUFFER data error ret -22

While with your instructions, I will try to use patch / upgrade the kernel. 
By the way, do the "2 options" you mentioned means either of them may solve the problem (E.g use Kernel 4.x with patch or just upgrade to Kernel 5.4 without using patch) ? Or both of them shall be deployed to solve the problem?

Thanks again, I'll update my progress after I tried those methods

Best Regards,
EasyPiggy

**Comment by arthur-simchaev-sndk** [comment]
Hi EasyPiggy


  1.  Seems your device doesn’t support the vendor command which you send . Clarify it with the device vendor.
The buf id, offset & buffer data.


  1.  .4 kernel already include ufs-bsg functionality, so you don’t need apply any patches.

Regards
Arthur
